### ISSUE TITLE
Unable to Install GIS4WRF plugin

### ISSUE THREAD

**Issue by bala-analytics** [GIS4WRF/gis4wrf#175]
**Describe the bug**
Unable to install GIS4WRF plugin.  Please see the attached screeshot of the error

**To Reproduce**
Followed the standard process of installing plugin.

The Error message:

Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

RuntimeError: GIS4WRF: Error installing Python packages Log: Added C:\Users\B.Bhaskaran\AppData\Local\gis4wrf\python37 as module search pathAdded C:\Users\B.Bhaskaran\AppData\Local\gis4wrf\python37\lib\site-packages as module search pathPackage directory: C:\Users\B.Bhaskaran\AppData\Local\gis4wrf\python37C:\Program Files\QGIS 3.14\bin\python-qgis.bat -m pip install --prefix C:\Users\B.Bhaskaran\AppData\Local\gis4wrf\python37 f90nml==1.0.2 netCDF4==1.4.2 https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whlCollecting f90nml==1.0.2   Using cached f90nml-1.0.2.tar.gz (45 kB) Collecting netCDF4==1.4.2   Using cached netCDF4-1.4.2-cp37-cp37m-win_amd64.whl (2.8 MB) Collecting wrf-python==1.3.2   ERROR: HTTP error 404 while getting https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl   ERROR: Could not install requirement wrf-python==1.3.2 from https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of error 404 Client Error: Not Found for url: https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl ERROR: Could not install requirement wrf-python==1.3.2 from https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of HTTP error 404 Client Error: Not Found for url: https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl for URL https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl 
Traceback (most recent call last):
  File "C:/Users/B.Bhaskaran/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 39, in bootstrap_with_ui
    for msg_type, msg_val in bootstrap():
  File "C:/Users/B.Bhaskaran/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\bootstrap.py", line 220, in bootstrap
    for line in run_subprocess(args, LOG_PATH):
  File "C:/Users/B.Bhaskaran/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\bootstrap.py", line 249, in run_subprocess
    raise subprocess.CalledProcessError(process.returncode, args)
subprocess.CalledProcessError: Command '['C:\\Program Files\\QGIS 3.14\\bin\\python-qgis.bat', '-m', 'pip', 'install', '--prefix', 'C:\\Users\\B.Bhaskaran\\AppData\\Local\\gis4wrf\\python37', 'f90nml==1.0.2', 'netCDF4==1.4.2', 'https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/B.Bhaskaran/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 22, in classFactory
    bootstrap_with_ui(iface)
  File "C:/Users/B.Bhaskaran/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 62, in bootstrap_with_ui
    raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
RuntimeError: GIS4WRF: Error installing Python packages
Log:
Added C:\Users\B.Bhaskaran\AppData\Local\gis4wrf\python37 as module search pathAdded C:\Users\B.Bhaskaran\AppData\Local\gis4wrf\python37\lib\site-packages as module search pathPackage directory: C:\Users\B.Bhaskaran\AppData\Local\gis4wrf\python37C:\Program Files\QGIS 3.14\bin\python-qgis.bat -m pip install --prefix C:\Users\B.Bhaskaran\AppData\Local\gis4wrf\python37 f90nml==1.0.2 netCDF4==1.4.2 https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whlCollecting f90nml==1.0.2
  Using cached f90nml-1.0.2.tar.gz (45 kB)
Collecting netCDF4==1.4.2
  Using cached netCDF4-1.4.2-cp37-cp37m-win_amd64.whl (2.8 MB)
Collecting wrf-python==1.3.2
  ERROR: HTTP error 404 while getting https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl
  ERROR: Could not install requirement wrf-python==1.3.2 from https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of error 404 Client Error: Not Found for url: https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl
ERROR: Could not install requirement wrf-python==1.3.2 from https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of HTTP error 404 Client Error: Not Found for url: https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl for URL https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.14.1-Pi Pi, de08d6b71d 

**Expected behavior**
Expected the plugin to be installed

**Screenshots**
![image](https://user-images.githubusercontent.com/62696358/88408123-05591200-cdcb-11ea-8324-cf5d609ca26c.png)

**System Information (please complete the following information):**
 - OS: Windows 10
 - QGIS: 3.14.1-PI

**Comment by bala-analytics** [comment]
I see this has been reported in #153 and appeared to have been fixed.  However, I still do have this problem.

**Comment by letmaik** [comment]
Thanks for bringing this up. I can confirm that this is broken currently. Since wrf-python is not maintained anymore, the simplest may be to just remove this from the automatic dependency install. If wrf-python still happens to be available on the system (because a user manually pip install'd it), that's fine, but if not, then the relevant functionality (extra derived fields when visualizing WRF files) will be disabled.

**Comment by dmey** [comment]
@bala-analytics version 0.14.3 is now available, please restart QGIS and install GIS4WRF 0.14.3.
